apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-3-apiusers
  labels:
    app: udacity-3-apiusers
spec:
  replicas: 2
  selector:
    matchLabels:
      app: udacity-3-apiusers
  template:
    metadata:
      labels:
        app: udacity-3-apiusers
    spec:
      containers:
      - name: udacity-3-apiusers
        image: fjenkel/udacity-3-apiusers
        ports:
        - containerPort: 8080