apiVersion: apps/v1
kind: Deployment
metadata:
  name: udacity-3-apiusers-pg
  labels:
    app: udacity-3-apiusers-pg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: udacity-3-apiusers-pg
  template:
    metadata:
      labels:
        app: udacity-3-apiusers-pg
    spec:
      containers:
        - name: postgres
          image: postgres:10.4
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: api-users-scr
                  key: postgres-username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: api-users-scr
                  key: postgres-password
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: api-users-scr
                  key: postgres-db