apiVersion: v1
kind: Service
metadata:
  labels:
    service: apiusers-pg
  name: apiusers-pg-svc
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    service: apiusers-pg
