apiVersion: v1
kind: Service
metadata:
  labels:
    service: apiusers
  name: apiusers-svc
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    app: udacity-3-apiusers
